package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/rafi/distributed-system-project/src/ServerObjectInterface.idl
* Monday, March 4, 2019 9:05:50 o'clock PM EST
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
