package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/rafi/distributed-system-project/src/ServerObjectInterface.idl
* Monday, March 4, 2019 9:05:50 o'clock PM EST
*/

public interface ServerObjectInterfaceOperations 
{
  boolean addItem (String managerID, String itemID, String itemName, int quantity);
  String listItem (String managerID);
  boolean removeItem (String managerID, String itemID, int quantity);
  boolean borrowItem (String userID, String itemID, int numberOfDay);
  String findItem (String userID, String itemName);
  boolean returnItem (String userID, String itemID);
  boolean waitingList (String userID, String itemID);
  String findBorrowedItems (String userId);
  String findWaitingItems ();
  boolean exchangeItem (String userID, String newItemID, String oldItemID);
  void shutdown ();
} // interface ServerObjectInterfaceOperations
